### PR TITLE
added support for materialgroup

### PR DESCRIPTION
**Pull request by dschoerk**

### CODE REVIEW

**Review by marceloclp — CHANGES_REQUESTED** [review]
This is an excellent idea. I just updated to v2 and there were major changes to the API, and files structure. Could you update to the new version? This is what has to be done:

- Move parser/scrapers methods to `src/Parser.js`.
- Add an export to MaterialGroup in `src/index.js`.

Sorry I just released a major update out of nowhere D:

**Comment by dschoerk** [comment]
thanks for the pointers. i'll probably have time to look at it during the weekend. may i ask why you switched to bddatabase?

**Comment by marceloclp** [comment]
Yeah, I changed because of the following reasons:

* BDDatabase is more consistent with the html, which makes it easier to scrape the data.
* When making multiple request simultaneously, BDOCodex would start throwing TIMEOUT errors and all following requests would fail for 3-4 minutes.
* BDDatabase on the other hand, seems to handle 50+ requests simultaneously without any problems.

I am developing another application which needs to make a considerable amount of requests simultaneously, so BDOCodex really wasn't working for me.

I am aware about the situation between BDOCodex and BDDatabase, so I really wanted to stick with BDOCodex.

**Comment by dschoerk** [comment]
merged, added material groups and tests for it

**Comment by marceloclp** [comment]
Very good. Just a few styling pointers that I would like you to change:

* Change `Materialgroup` to `MaterialGroup` at `module.exports` at `src/index.js`.
* Change `getMaterialgroup` to `getMaterialGroup` at `src/Parser.js`.

If you are up to it, it would be interesting to get `icon` for each material as well.

Good job.

**Comment by dschoerk** [comment]
requested changes added
added material group icon with the icon of the first material, materialgroup itself does not have an icon
merged for fast forward

**Pull request merged**
